CC=gcc
TARGET=main
CFLAG=-Wall

ex112:
	$(CC) $(CFLAG) ex112.c -o ex112

ex117:
	$(CC) $(CFLAG) ex117.c -o ex117

ex118:
	$(CC) $(CFLAG) ex118.c -o ex118

ex119:
	$(CC) $(CFLAG) ex119.c -o ex119

clean:
	rm *.o $(TARGET)